language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - "2.7"
env:
  matrix:
    - PLONE_VERSION=4.3
    - PLONE_VERSION=5.0
    - PLONE_VERSION=5.1
matrix:
  fast_finish: true
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - sed -ie "s#4.3-latest#$PLONE_VERSION-latest#" buildout.cfg
  - sed -ie "s#versions-4.3#versions-$PLONE_VERSION#" buildout.cfg
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test
  - bin/pylint --py3k --disable=no-absolute-import src/collective/restapi/navigationtree || true
after_success:
  - bin/createcoverage --output-dir=htmlcov -t "--layer=\!Robot"
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
